# Generated by Django 4.2.7 on 2023-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='nulo', max_length=255),
        ),
    ]
