# Generated by Django 4.2.7 on 2023-12-02 20:23

import core.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(max_length=1000, verbose_name='descrição')),
                ('priority', enumchoicefield.fields.EnumChoiceField(default=core.models.Priority(3), enum_class=core.models.Priority, max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
